org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Dependency versions
tiktoklive_version=1.11.12-Release
tiktoklive_jar_path=libs/Client-1.11.12-Release-all.jar
tiktoklive_sha512=ce3df82601dd85bd130fc80f7baf19128ebe8737fb671b60e560f5ad5e997c0aaee60230657ef198865838c8ac85a25baaa62ad7186f104ca34f23df55ccffd3

## Version ranges (used in mods.toml)
minecraft_version_range=[1.20.1,1.21)
forge_version_range=[47,)
loader_version_range=[47,)

## Mod Properties
artifact_base_name=reinodoce-mc-tiktok
mod_id=reinodoce_mctiktok
mod_name=Reino Doce MC TikTok
mod_license=LGPL-3.0-or-later
mod_version=0.1.4
mod_group_id=br.com.reinodoce.mctiktok
mod_authors=Reino Doce
mod_description=Client-side only Forge mod that mirrors TikTok LIVE chat into Minecraft local chat.
modrinth_project_id=OrIKDIK6
